language: python

services:
  - docker

python:
  - "3.6"

env:
  global:
    - DOCKER_IMAGE_PREFIX=qwantresearch/kartotherian
  matrix:
    - SERVICE=linter
    - SERVICE=test
    - SERVICE=load_db
    - SERVICE=tilerator
    - SERVICE=kartotherian
    - SERVICE=telegraf

before_install:
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    fi

script: >
    if [ "$SERVICE" == "linter" ]; then
        pip install --pre black=="20.8b1"
        black --diff --check .
    elif [ "$SERVICE" == "test" ]; then
        ./exec.py --debug load-db \
            --env INVOKE_WIKIDATA_STATS_ENABLED=0 \
            --osm-file https://download.geofabrik.de/europe/monaco-latest.osm.pbf \
            --tiles-coords "[[266, 186, 9]]"
        ./exec.py --debug --no-build test
    else
        export DOCKER_IMAGE="${DOCKER_IMAGE_PREFIX}_$SERVICE"
        docker build --label "org.label-schema.vcs-ref=$TRAVIS_COMMIT" -t $DOCKER_IMAGE -f ./$SERVICE/Dockerfile .

        if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
            docker push $DOCKER_IMAGE;
        fi
    fi
