services:
  - docker

env:
  global:
    - DOCKER_IMAGE_PREFIX=qwantresearch/kartotherian
  matrix:
    - SERVICE=load_db
    - SERVICE=tilerator
    - SERVICE=kartotherian
    - SERVICE=telegraf

branches:
  only:
    - master

before_install:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export DOCKER_IMAGE="${DOCKER_IMAGE_PREFIX}_$SERVICE"
  - docker build --label "org.label-schema.vcs-ref=$TRAVIS_COMMIT" -t $DOCKER_IMAGE ./$SERVICE
  - docker push $DOCKER_IMAGE
