apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - image: cassandra:latest
        name: cassandra
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: csdata
      restartPolicy: Always
      volumes:
      - name: csdata
        persistentVolumeClaim:
          claimName: csdata
status: {}
