apiVersion: v1
kind: Pod
metadata:
  name: cassandra
spec:
  containers:
  - name: cassandra
    image: cassandra:latest
    volumeMounts:
    - mountPath: "/var/lib/cassandra"
      name: csdata
  volumes:
    - name: csdata
