apiVersion: v1
kind: Service
metadata:
  labels:
    svc: cassandra
  name: cassandra
spec:
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    svc: cassandra
status:
  loadBalancer: {}
