apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest
        volumeMounts:
        - mountPath: "/var/lib/cassandra"
          name: csdata
        ports:
        - containerPort: 9042
      volumes:
        - name: csdata
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: cassandra
