apiVersion: v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - args:
        - redis-server
        - --appendonly
        - "yes"
        image: redis:latest
        name: redis
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redisdata
      restartPolicy: Always
      volumes:
      - name: redisdata
        persistentVolumeClaim:
          claimName: redisdata
status: {}
