apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    command: ["redis-server"]
    args: ["--appendonly", "yes"]
    volumeMounts:
    - mountPath: "/data"
      name: redisdata
  volumes:
    - name: redisdata
