apiVersion: v1
kind: Pod
metadata:
  name: tilerator
spec:
  containers:
  - name: redis
    image: redis:latest
    command: ["redis-server"]
    args: ["--appendonly", "yes"]
    volumeMounts:
    - mountPath: "/data"
      name: redisdata
  - name: cassandra
    image: cassandra:latest
    volumeMounts:
    - mountPath: "/var/lib/cassandra"
      name: csdata
  - name: tilerator
    image: jbunss/tilerator:k8s
    env:
      - name: NODE_PATH
        value: "/opt/tilerator/node_modules"
      - name: TILERATOR_PORT
        value: "16354"
  volumes:
    - name: redisdata
    - name: csdata
