apiVersion: v1
kind: Pod
metadata:
  name: tilerator
spec:
  containers:
  - name: tilerator
    image: jbunss/tilerator:k8s
    env:
      - name: NODE_PATH
        value: "/opt/tilerator/node_modules"
      - name: TILERATOR_PORT
        value: "16354"
