apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: tilerator
  name: tilerator
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: tilerator
    spec:
      containers:
      - name: tilerator
        env:
        - name: NODE_PATH
          value: '''/opt/tilerator/node_modules'''
        - name: TILERATOR_PORT
          value: "16354"
        image: jbunss/tilerator:k8s
        ports:
        - containerPort: 16534
        resources: {}
      restartPolicy: Always
status: {}
