# Generates vtiles from database
gen:
  public: true
  formats: [pbf]
  uri: bridge://
  xml: '/housenumber.xml'
    # npm: ["@kartotherian/osm-bright-source", "data.xml"]
  xmlSetDataSource:
    if:
      dbname: gis
      host: ''
      type: postgis
    set:
      host: postgres
      user: {var: osmdb-user}
      password: {var: osmdb-pswd}

ozgen:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: gen}

# View tiles as generated directly from the database. Don't view zoom0-5
genview:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    loader: "@kartotherian/osm-bright-style"
  xmlSetParams:
    source: {ref: gen}

v2:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 16
    keyspace: v2
    cp: {var: cassandra-servers}
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true

# View tiles as generated directly from the database. Don't view zoom0-5
v2view:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    loader: "@kartotherian/osm-bright-style"
  xmlSetParams:
    source: {ref: v2}

dyn:
  uri: autogen://
  params:
    storage: {ref: v2}
    generator: {ref: gen}
    # Optional:
    mingen: 10  # Only generate tiles if missing within this zoom range
    maxgen: 15
    minstore: 10  # if generated, only store them if within this zoom range 
    maxstore: 15

oz:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: dyn}

osm-intl:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml: '/omt_osm_bright.xml'
  # xml:
  #   # loader: "@kartotherian/osm-bright-style"
  #   # npmpath: ["@mapbox/mapbox-studio-osm-bright", "project.xml"]
  xmlSetParams:
    source: {ref: ozgen}

mix:
  uri: demultiplexer://
  params:
    source1: {ref: v2}
    from1: 0
    before1: 9
    source2: {ref: gen}
    from2: 9
    before2: 19

mixview:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    loader: "@kartotherian/osm-bright-style"
  xmlSetParams:
    source: {ref: mix}

